brokers = ['localhost:42019']

[stream]
input = ['in1','in2']
output = ['out1', 'out2']
steps = ["no-filter-values", "show-values", "transformer-values", "sample"]

[no-filter-values]
module = 'jq-filter'
params = 'false'

[filter-all-values]
module = 'jq-filter'
params = 'true'

[show-values]
module = 'log'

[transformer-values]
module = 'jq-transformer'
params = '.'

[sample]
module = 'sample'