[stream]
input = ['in1','in2']
output = ['out1', 'out2']
operations = ["filter-values", "show-values", "transformer-values"]

[filter-values]
module = 'jq-filter'
params = 'true'

[show-values]
module = 'log'

[transformer-values]
module = 'jq-processor'
params = [".", "true"]
